#!/bin/bash
# Set job parameters
#SBATCH -p General
#SBATCH --time=2:00:00
#SBATCH -J  tio2-rutile
#SBATCH -o  tio2-rutile.o%J
#SBATCH -e  tio2-rutile.e%J
#SBATCH -n 16
#SBATCH -N 1
#SBATCH --mem-per-cpu=2G
module purge
module load intel/intel-2016-update2
module load mpich/mpich-3.2-intel
module load vasp/vasp-5.4.1-intel
# Start MPI job
mpirun vasp_gam >> vasp.out
